version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: payload_cms
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
